
HEALTH_TIPS = [
    "Drink at least 8 glasses of water daily to stay hydrated and support bodily functions.",
    "Aim for 7-9 hours of quality sleep each night for optimal physical and mental health.",
    "Incorporate 30 minutes of moderate exercise into your daily routine.",
    "Eat a balanced diet rich in fruits, vegetables, and whole grains.",
    "Practice mindfulness meditation for 10-15 minutes daily to reduce stress.",
    "Take regular breaks from screens to protect your eye health.",
    "Wash your hands frequently to prevent the spread of germs and illnesses.",
    "Maintain good posture while sitting to prevent back and neck pain.",
    "Get regular health check-ups and screenings as recommended for your age.",
    "Limit processed foods and opt for whole, natural foods instead.",
    "Practice deep breathing exercises to manage stress and improve lung capacity.",
    "Stay socially connected with friends and family for mental well-being.",
    "Protect your skin from sun exposure by using sunscreen daily.",
    "Stretch regularly to maintain flexibility and prevent muscle stiffness.",
    "Limit alcohol consumption and avoid smoking for better long-term health.",
    "Practice good dental hygiene by brushing twice daily and flossing.",
    "Take the stairs instead of the elevator when possible for extra activity.",
    "Stay mentally active by reading, puzzles, or learning new skills.",
    "Maintain a healthy weight through balanced nutrition and regular exercise.",
    "Practice gratitude daily to improve mental health and perspective.",
    "Stay hydrated with water instead of sugary drinks.",
    "Get some sunlight exposure daily for vitamin D, but avoid peak hours.",
    "Practice proper lifting techniques to prevent back injuries.",
    "Limit caffeine intake, especially in the afternoon and evening.",
    "Cook meals at home to control ingredients and portion sizes.",
    "Stay up to date with recommended vaccinations.",
    "Practice safe food handling and preparation techniques.",
    "Wear appropriate protective gear during sports and physical activities.",
    "Manage your time effectively to reduce stress and improve work-life balance.",
    "Listen to your body and rest when you feel tired or unwell."
    "Include probiotic-rich foods like yogurt in your diet for gut health.",
    "Practice portion control to maintain a healthy weight and prevent overeating.",
    "Stand up and move around every hour if you have a sedentary job.",
    "Get your blood pressure checked regularly to monitor cardiovascular health.",
    "Include omega-3 fatty acids in your diet for brain and heart health.",
    "Practice good sleep hygiene by keeping your bedroom dark and quiet.",
    "Learn to recognize early signs of stress and address them promptly.",
    "Include strength training exercises at least twice a week.",
    "Practice mindful eating by paying attention to your food without distractions.",
    "Get your vision checked annually to maintain eye health.",
    "Include fiber-rich foods in your diet for better digestion.",
    "Practice good foot hygiene and wear comfortable, supportive shoes.",
    "Limit sodium intake to support heart health and blood pressure.",
    "Practice regular self-examinations for early detection of health issues.",
    "Include antioxidant-rich foods like berries in your diet.",
    "Practice good ear hygiene and protect your hearing in loud environments.",
    "Get regular dental cleanings every six months.",
    "Practice good hand hygiene to prevent the spread of infections.",
    "Include calcium-rich foods for strong bones and teeth.",
    "Practice good posture while standing and walking.",
    "Limit exposure to environmental toxins and pollutants.",
    "Practice regular cardiovascular exercise for heart health.",
    "Include iron-rich foods in your diet to prevent anemia.",
    "Practice good nasal hygiene and use saline sprays if needed.",
    "Get adequate vitamin C through fruits and vegetables for immune support.",
    "Practice good hair and scalp care for overall hygiene.",
    "Include protein in every meal for sustained energy.",
    "Practice regular balance exercises to prevent falls.",
    "Get adequate vitamin A for good vision and skin health.",
    "Practice good nail care and hygiene.",
    "Include whole grains for sustained energy and fiber.",
    "Practice regular flexibility exercises like yoga or tai chi.",
    "Get adequate B vitamins for energy and brain function.",
    "Practice good oral hygiene after every meal.",
    "Include healthy fats like avocado and nuts in your diet.",
    "Practice regular relaxation techniques to manage stress.",
    "Get adequate vitamin E for skin and immune health.",
    "Practice good skin care routine for healthy complexion.",
    "Include a variety of colorful vegetables in your meals.",
    "Practice regular mental health check-ins with yourself.",
    "Get adequate zinc for immune function and wound healing.",
    "Practice good sleep schedule consistency, even on weekends.",
    "Include fermented foods for gut microbiome health.",
    "Practice regular social activities for emotional well-being.",
    "Get adequate magnesium for muscle and nerve function.",
    "Practice good breathing techniques throughout the day.",
    "Include lean protein sources in your diet.",
    "Practice regular digital detox to reduce screen time.",
    "Get adequate potassium for heart and muscle function.",
    "Practice good water intake tracking throughout the day.",
    "Include herbs and spices for flavor instead of excess salt.",
    "Practice regular nature exposure for mental well-being.",
    "Get adequate selenium for thyroid and immune health.",
    "Practice good meal planning for healthier eating habits.",
    "Include plant-based proteins in your diet regularly.",
    "Practice regular laughter and humor for stress relief.",
    "Get adequate vitamin K for bone and blood health.",
    "Practice good stress management techniques daily.",
    "Include complex carbohydrates for sustained energy.",
    "Practice regular mindfulness throughout your day.",
    "Get adequate phosphorus for bone and cell health.",
    "Practice good hydration habits before feeling thirsty.",
    "Include a variety of nuts and seeds in your diet.",
    "Practice regular positive self-talk and affirmations.",
    "Get adequate copper for iron absorption and energy.",
    "Practice good ergonomics at your workstation.",
    "Include dark leafy greens in your meals regularly.",
    "Practice regular gratitude journaling for mental health.",
    "Get adequate manganese for bone development and metabolism.",
    "Practice good portion awareness when eating out.",
    "Include a variety of beans and legumes in your diet.",
    "Practice regular deep breathing for relaxation.",
    "Get adequate chromium for blood sugar regulation.",
    "Practice good food label reading for healthier choices.",
    "Include a variety of mushrooms for immune support.",
    "Practice regular stretching breaks during long sits.",
    "Get adequate molybdenum for enzyme function.",
    "Practice good meal timing for optimal digestion.",
    "Include a variety of seeds like chia and flax in your diet.",
    "Practice regular posture checks throughout the day.",
    "Get adequate iodine for thyroid function.",
    "Practice good snack preparation for healthy options.",
    "Include a variety of whole fruits in your diet.",
    "Practice regular eye rest during screen time.",
    "Get adequate fluoride for dental health.",
    "Practice good breathing posture for lung capacity.",
    "Include a variety of seafood for omega-3s.",
    "Practice regular foot exercises for circulation.",
    "Get adequate vitamin D through sunlight or supplements.",
    "Practice good sleep position for spinal health.",
    "Include a variety of peppers for vitamin C.",
    "Practice regular hand exercises for flexibility.",
    "Get adequate biotin for hair and nail health.",
    "Practice good walking technique for joint health.",
    "Include a variety of root vegetables in your meals.",
    "Practice regular shoulder rolls to prevent tension.",
    "Get adequate folate for cell growth and function.",
    "Practice good chewing habits for better digestion.",
    "Include a variety of citrus fruits for vitamin C.",
    "Practice regular neck stretches to prevent stiffness.",
    "Get adequate riboflavin for energy production.",
    "Practice good water quality awareness for health.",
    "Include a variety of cruciferous vegetables regularly.",
    "Practice regular wrist exercises for carpal tunnel prevention.",
    "Get adequate thiamine for nerve function.",
    "Practice good food storage for safety and freshness.",
    "Include a variety of berries for antioxidants.",
    "Practice regular ankle rotations for joint health.",
    "Get adequate niacin for cholesterol management.",
    "Practice good cooking methods to preserve nutrients.",
    "Include a variety of tropical fruits in your diet.",
    "Practice regular knee bends for joint mobility.",
    "Get adequate pantothenic acid for hormone production.",
    "Practice good food combining for optimal digestion.",
    "Include a variety of melons for hydration.",
    "Practice regular hip stretches for flexibility.",
    "Get adequate choline for brain health.",
    "Practice good meal variety for nutritional balance.",
    "Include a variety of stone fruits in season.",
    "Practice regular back strengthening exercises.",
    "Get adequate vitamin B12 for nerve health.",
    "Practice good eating environment for mindful meals.",
    "Include a variety of pomegranates for antioxidants.",
    "Practice regular core exercises for stability.",
    "Get adequate vitamin B6 for mood regulation.",
    "Practice good food preparation hygiene.",
    "Include a variety of apples for fiber and antioxidants.",
    "Practice regular leg stretches for circulation.",
    "Get adequate CoQ10 for heart health.",
    "Practice good meal pacing for better digestion.",
    "Include a variety of pears for digestive health.",
    "Practice regular arm circles for shoulder health.",
    "Get adequate lycopene from tomatoes for heart health.",
    "Practice good hydration with electrolytes when needed.",
    "Include a variety of grapes for heart health.",
    "Practice regular full-body stretches daily.",
    "Get adequate resveratrol from red grapes for antioxidants.",
    "Practice good breathing rhythm during exercise.",
    "Include a variety of kiwis for vitamin C.",
    "Practice regular joint mobility exercises.",
    "Get adequate lutein from leafy greens for eye health.",
    "Practice good recovery after physical activity.",
    "Include a variety of pineapples for digestion.",
    "Practice regular balance training for stability.",
    "Get adequate zeaxanthin from corn for eye health.",
    "Practice good warm-up before exercise.",
    "Include a variety of mangoes for vitamin A.",
    "Practice regular cool-down after workouts.",
    "Get adequate astaxanthin from seafood for skin health.",
    "Practice good exercise form to prevent injuries.",
    "Include a variety of papayas for digestion.",
    "Practice regular flexibility training.",
    "Get adequate beta-carotene from carrots for vision.",
    "Practice good rest days for muscle recovery.",
    "Include a variety of bananas for potassium.",
    "Practice regular movement throughout your day.",
    "Get adequate quercetin from onions for anti-inflammatory benefits.",
    "Practice good sleep environment optimization.",
    "Include a variety of avocados for healthy fats.",
    "Practice regular stress reduction activities.",
    "Get adequate curcumin from turmeric for inflammation.",
    "Practice good sunlight protection when outdoors.",
    "Include a variety of olives for heart-healthy fats.",
    "Practice regular mental stimulation activities.",
    "Get adequate gingerol from ginger for digestion.",
    "Practice good air quality in your living spaces.",
    "Include a variety of dates for natural sweetness.",
    "Practice regular social connection for well-being.",
    "Get adequate allicin from garlic for immune support.",
    "Practice good noise management for hearing health.",
    "Include a variety of figs for fiber and minerals.",
    "Practice regular self-care routines.",
    "Get adequate capsaicin from chili peppers for metabolism.",
    "Practice good temperature regulation for comfort.",
    "Include a variety of prunes for digestive health.",
    "Practice regular health goal setting.",
    "Get adequate sulforaphane from broccoli for detoxification.",
    "Practice good emotional awareness and expression.",
    "Include a variety of apricots for vitamin A.",
    "Practice regular health monitoring and tracking.",
    "Get adequate anthocyanins from blueberries for brain health.",
    "Practice good conflict resolution skills.",
    "Include a variety of plums for antioxidants.",
    "Practice regular positive thinking habits.",
    "Get adequate ellagic acid from raspberries for cancer prevention.",
    "Practice good time management for reduced stress.",
    "Include a variety of cherries for sleep support.",
    "Practice regular deep sleep optimization.",
    "Get adequate proanthocyanidins from cranberries for urinary health.",
    "Practice good relationship maintenance.",
    "Include a variety of peaches for hydration.",
    "Practice regular health education and learning.",
    "Get adequate catechins from green tea for antioxidants.",
    "Practice good financial health for reduced stress.",
    "Include a variety of nectarines for vitamin C.",
    "Practice regular community involvement.",
    "Get adequate theanine from tea for relaxation.",
    "Practice good environmental awareness.",
    "Include a variety of persimmons for fiber.",
    "Practice regular health advocacy for yourself.",
    "Get adequate glucosinolates from cabbage for liver health.",
    "Practice good personal boundaries for well-being.",
    "Include a variety of guavas for vitamin C.",
    "Practice regular health prevention measures.",
    "Get adequate betalains from beets for inflammation.",
    "Practice good life balance across all areas.",
    "Include a variety of starfruit for antioxidants.",
    "Practice regular health maintenance routines.",
    "Get adequate shogaol from ginger for pain relief.",
    "Practice good coping mechanisms for stress.",
    "Include a variety of lychees for vitamin C.",
    "Practice regular health improvement efforts.",
    "Get adequate piperine from black pepper for nutrient absorption.",
    "Practice good decision-making for health choices.",
    "Include a variety of rambutans for minerals.",
    "Practice regular health optimization strategies.",
    "Get adequate eugenol from cloves for dental health.",
    "Practice good problem-solving skills.",
    "Include a variety of longans for relaxation.",
    "Practice regular health awareness and education.",
    "Get adequate thymol from thyme for respiratory health.",
    "Practice good communication for relationships.",
    "Include a variety of jackfruit for fiber.",
    "Practice regular health screening compliance.",
    "Get adequate carvacrol from oregano for antimicrobial benefits.",
    "Practice good self-reflection habits.",
    "Include a variety of durian for nutrients.",
    "Practice regular health habit formation.",
    "Get adequate rosmarinic acid from rosemary for brain health.",
    "Practice good emotional regulation skills.",
    "Include a variety of breadfruit for carbohydrates.",
    "Practice regular health risk assessment.",
    "Get adequate cinnamaldehyde from cinnamon for blood sugar.",
    "Practice good resilience building.",
    "Include a variety of soursop for antioxidants.",
    "Practice regular health priority setting.",
    "Get adequate menthol from mint for digestion.",
    "Practice good adaptability to change.",
    "Include a variety of passion fruit for fiber.",
    "Practice regular health consultation when needed.",
    "Get adequate anethole from fennel for digestion.",
    "Practice good prevention mindset.",
    "Include a variety of dragon fruit for antioxidants.",
    "Practice regular health monitoring.",
    "Get adequate limonene from citrus peels for mood.",
    "Practice good health information evaluation.",
    "Include a variety of kiwanos for hydration.",
    "Practice regular health action taking.",
    "Get adequate apigenin from parsley for inflammation.",
    "Practice good health responsibility.",
    "Include a variety of horned melon for electrolytes.",
    "Practice regular health improvement tracking.",
    "Get adequate luteolin from celery for brain health.",
    "Practice good health consistency.",
    "Include a variety of feijoas for vitamin C.",
    "Practice regular health celebration of progress.",
    "Get adequate hesperidin from oranges for blood vessels.",
    "Practice good health persistence.",
    "Include a variety of quinces for fiber.",
    "Practice regular health adaptation.",
    "Get adequate naringenin from grapefruit for metabolism.",
    "Practice good health innovation.",
    "Include a variety of medlars for antioxidants.",
    "Practice regular health exploration.",
    "Get adequate rutin from buckwheat for circulation.",
    "Practice good health curiosity.",
    "Include a variety of jujubes for relaxation.",
    "Practice regular health experimentation.",
    "Get adequate myricetin from berries for brain health.",
    "Practice good health open-mindedness.",
    "Include a variety of mulberries for antioxidants.",
    "Practice regular health learning.",
    "Get adequate kaempferol from kale for heart health.",
    "Practice good health humility.",
    "Include a variety of elderberries for immunity.",
    "Practice regular health gratitude.",
    "Get adequate fisetin from strawberries for brain health.",
    "Practice good health patience.",
    "Include a variety of goji berries for antioxidants.",
    "Practice regular health compassion for yourself.",
    "Get adequate genistein from soy for bone health.",
    "Practice good health forgiveness.",
    "Include a variety of acai berries for antioxidants.",
    "Practice regular health kindness to yourself.",
    "Get adequate daidzein from soy for menopause symptoms.",
    "Practice good health acceptance.",
    "Include a variety of maqui berries for antioxidants.",
    "Practice regular health self-love.",
    "Get adequate glycitein from soy for skin health.",
    "Practice good health balance.",
    "Include a variety of seabuckthorn for omega-7.",
    "Practice regular health harmony.",
    "Get adequate enterodiol from flaxseeds for hormone balance.",
    "Practice good health integration.",
    "Include a variety of camu camu for vitamin C.",
    "Practice regular health wholeness.",
    "Get adequate enterolactone from sesame seeds for cancer prevention.",
    "Practice good health fulfillment.",
    "Include a variety of baobab for vitamin C.",
    "Practice regular health joy.",
    "Get adequate equol from soy for antioxidant benefits.",
    "Practice good health vitality.",
    "Include a variety of noni fruit for antioxidants.",
    "Practice regular health energy management.",
    "Get adequate urolithin from pomegranates for muscle health.",
    "Practice good health rhythm.",
    "Include a variety of mangosteen for antioxidants.",
    "Practice regular health flow.",
    "Get adequate hydroxytyrosol from olives for heart health.",
    "Practice good health alignment.",
    "Include a variety of tamarind for digestion.",
    "Practice regular health coherence.",
    "Get adequate oleuropein from olive leaves for immunity.",
    "Practice good health synchronization.",
    "Include a variety of carob for antioxidants.",
    "Practice regular health optimization.",
    "Get adequate oleocanthal from olive oil for inflammation.",
    "Practice good health maximization.",
    "Include a variety of mesquite for fiber.",
    "Practice regular health enhancement.",
    "Get adequate tyrosol from olive oil for longevity.",
    "Practice good health amplification.",
    "Include a variety of lucuma for antioxidants.",
    "Practice regular health elevation.",
    "Get adequate verbascoside from olive oil for skin health.",
    "Practice good health transcendence.",
    "Include a variety of yacon for prebiotics.",
    "Practice regular health excellence.",
    "Get adequate ligstroside from olive oil for antioxidants.",
    "Practice good health mastery.",
    "Include a variety of maca for energy.",
    "Practice regular health achievement.",
    "Get adequate demethoxycurcumin from turmeric for inflammation.",
    "Practice good health success.",
    "Include a variety of spirulina for protein.",
    "Practice regular health accomplishment.",
    "Get adequate bisdemethoxycurcumin from turmeric for joints.",
    "Practice good health victory.",
    "Include a variety of chlorella for detoxification.",
    "Practice regular health triumph.",
    "Get adequate gingerdiol from ginger for nausea.",
    "Practice good health celebration.",
    "Include a variety of wheatgrass for chlorophyll.",
    "Practice regular health appreciation.",
    "Get adequate shogaols from ginger for pain.",
    "Practice good health recognition.",
    "Include a variety of barley grass for nutrients.",
    "Practice regular health acknowledgment.",
    "Get adequate paradols from ginger for antioxidants.",
    "Practice good health validation.",
    "Include a variety of alfalfa for minerals.",
    "Practice regular health confirmation.",
    "Get adequate zingerone from ginger for inflammation.",
    "Practice good health affirmation.",
    "Include a variety of moringa for vitamins.",
    "Practice regular health reinforcement.",
    "Get adequate galanolactone from ginger for digestion.",
    "Practice good health consolidation.",
    "Include a variety of ashwagandha for stress relief.",
    "Practice regular health stabilization.",
    "Get adequate gingerol from ginger for metabolism.",
    "Practice good health foundation building.",
    "Include a variety of rhodiola for energy.",
    "Practice regular health grounding.",
    "Get adequate shogaol from ginger for pain relief.",
]

def get_random_tip():
    """Return a random health tip"""
    import random
    return random.choice(HEALTH_TIPS)

def get_all_tips():
    """Return all health tips"""
    return HEALTH_TIPS.copy()