# Generated by Django 5.0.14 on 2025-10-31 00:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTipDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tip_content', models.TextField()),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('context_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'health_tip_deliveries',
                'ordering': ['-delivery_time'],
            },
        ),
    ]
